---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: 201096
    password: 1de8bf08-86e8-4e4f-9365-3d301199b6d6

- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: 201096/cd
    tag: end
    push: yes
